### ISSUE TITLE
README.rb:  "root_home" should be "home_root"

### ISSUE THREAD

**Issue by flatrocks** [tamucookbooks/user_account#1]
In the README.rb file, under attributes, the key for "default root home path" is shown as:

```
['user_account']['root_home']
```

Seems like this should be:

```
['user_account']['home_root']
```

(This will cause problems for anyone trying to use `"#{node['user_account']['home_root']}/#{ current_resource.user}` or similar to calculate the home directory.)

**Comment by jarosser06** [comment]
Thanks I'll fix this

**Comment by jarosser06** [comment]
Fixed https://github.com/tamucookbooks/user_account/commit/b89f07eccd750d00ef6f05fe79cd6584530ae7e7
